### ISSUE TITLE
Boilerplate issue: SyntaxError: Unexpected token '&&='

### ISSUE THREAD

**Issue by alexjs-dev** [thirdweb-dev/js#1020]
Hello,

After following the documentation on adding Thirdweb-dev lib to NextJs:
https://portal.thirdweb.com/react/getting-started 
Node version: 16.16.0
Next version: 13.0.3

`pnpm @thirdweb-dev/react @thirdweb-dev/sdk ethers@^5`

and using simply as

```
...
import { ThirdwebProvider } from '@thirdweb-dev/react';
...
const MyApp = ({ Component, pageProps, token }: AppPropsExtended) => {
  return (
    <ReduxProvider store={store}>
      <ApolloProvider pageProps={pageProps} token={token}>
        <Dialog />
        <Toast />
        <ThirdwebProvider activeChain="ethereum"> {/* THIS PART CAUSES ERROR */
          <Component {...pageProps} />
        </ThirdwebProvider>
      </ApolloProvider>
    </ReduxProvider>
  );
};
```

I am getting this error:
```
/Users/aleksei/Documents/next/node_modules/.pnpm/@thirdweb-dev+sdk@3.10.14_mxuo2gdmcr3m5t45q7ow2glw5q/node_modules/@thirdweb-dev/sdk/dist/watchTransactions-e5d8e227.cjs.dev.js:6547
      foundError &&= error.includes(substring);
                 ^^^

SyntaxError: Unexpected token '&&='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/aleksei/Documents/next/node_modules/.pnpm/@thirdweb-dev+sdk@3.10.14_mxuo2gdmcr3m5t45q7ow2glw5q/node_modules/@thirdweb-dev/sdk/dist/thirdweb-dev-sdk.cjs.dev.js:6:25)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

It seems that NextJs isn't able to transpile the operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment

**Comment by MananTank** [comment]
@alexjs-dev - can you create a minimal repo where we can replicate this issue?
I tried but couldn't replicate it using your given Node and Next.js version

**Comment by lakgarg** [comment]
also can you try to update your node version @alexjs-dev, I replicated the issue a while ago and all I needed to do was update node in order to get past this!

**Comment by zerts** [comment]
I've managed to fix it by switching to node 18+

**Comment by MananTank** [comment]
Hi @alexjs-dev - Are you still facing this issue?

**Comment by DhaanishTts** [comment]
yes still facing the same issue
