### ISSUE TITLE
Sign Modal and Redirect Broken after update to 0.2.25

### ISSUE THREAD

**Issue by brien-crean** [thirdweb-dev/js#1272]
Broken after updating to the latest thirdweb packages as recommended to migrate to WalletConnect v2. The Sign Modal (in Metamask) does not appear, unless multiple calls to `login` from `useLogin` are made . Eventually after 3 or 4 attempts the sign modal will appear, allowing me to sign the login request and get a token. At that point the redirect back to the client does not occur.

App details
React Native 0.71.10 - React Native CLI (Non Expo)
Android 13 (Not using iOS)
Metamask Android app `7.1.0`

react native third web dependencies
```json
"@thirdweb-dev/react-native": "^0.2.25",
"@thirdweb-dev/react-native-compat": "^0.2.25",
```
`"@thirdweb-dev/auth": "^3.2.6"` on our API server

I also observe the same behaviour by while using the [react native starter app](https://github.com/rowbot-weisguy/react-native-typescript-starter). I updated the thirdweb dependencies of course.

```js
const {login} = useLogin();

const handleLogin = async () => {
    const token = await login();
    console.log('logged in, token', token);
 };
```

Here is the output when login is called:
```
 ERROR  {"context": "core"} {"context": "core/pairing"} {"context": "core/pairing/pairing"} No matching key. pairing: 303b58f2dedf452f7b440c7fb334f449b8538b9e59b9fe71c7737c7195d9a204
 ERROR  {"context": "client"} [Error: No matching key. pairing: 303b58f2dedf452f7b440c7fb334f449b8538b9e59b9fe71c7737c7195d9a204]
 ERROR  {"context": "core"} {"context": "core/pairing"} {"context": "core/pairing/pairing"} No matching key. pairing: 303b58f2dedf452f7b440c7fb334f449b8538b9e59b9fe71c7737c7195d9a204
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error: No matching key. pairing: 303b58f2dedf452f7b440c7fb334f449b8538b9e59b9fe71c7737c7195d9a204
Error: No matching key. pairing: 303b58f2dedf452f7b440c7fb334f449b8538b9e59b9fe71c7737c7195d9a204
    at getData (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:111219:48)
    at ?anon_0_ (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:111144:44)
    at next (native)
    at asyncGeneratorStep (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20751:26)
    at _next (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20770:29)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20775:14)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20767:25)
    at apply (native)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:111148:30)
    at ?anon_0_ (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:111378:65)
    at next (native)
    at asyncGeneratorStep (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20751:26)
    at _next (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20770:29)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20775:14)
    at tryCallTwo (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20767:25)
    at apply (native)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:111383:30)
    at ?anon_0_ (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:124686:155)
    at next (native)
    at asyncGeneratorStep (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20751:26)
    at _next (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:20770:29)
    at tryCallOne (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/root/react-native/ReactAndroid/hermes-engine/.cxx/Release/2q6r403w/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:26281:26)
    at _callTimer (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:26200:17)
    at _callReactNativeMicrotasksPass (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:26230:17)
    at callReactNativeMicrotasks (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:26393:44)
    at __callReactNativeMicrotasks (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:2517:46)
    at anonymous (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:2329:45)
    at __guard (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:2501:15)
    at flushedQueue (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:2328:21)
    at invokeCallbackAndReturnFlushedQueue (http://192.168.50.101:8081/index.bundle?platform=android&dev=true&minify=false&app=com.reactnativestarter&modulesOnly=false&runModule=true:2322:33)
```
After multiple attempts of going back to the app, calling login I eventually get the sign modal in metamask and a token, however the redirect to metamask also does not occur.

Also when logging out I get

```
[Error: missing response (requestBody="[{\"method\":\"eth_getBalance\",\"params\":[\"0xaa230911d57f49a70ec155fcec19b3b2e9716f5b\",\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}]", requestMethod="POST", serverError={}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.7.1)]
```

**Comment by jnsdls** [comment]
thanks for the report @brien-crean, we'll look at it ASAP

**Comment by iketw** [comment]
@brien-crean @T-Damer, I'm not able to 100% reproduce this but please not that there are currently some issues with WC/MM reported on their GitHub about sign dialogs not showing up:

https://github.com/MetaMask/metamask-mobile/issues/6701
https://github.com/MetaMask/metamask-mobile/issues/6655

https://github.com/WalletConnect/walletconnect-monorepo/issues/2789

As you mentioned, if this works with Trust and Rainbow that's a good signal it's on MM and not our SDK.

**Comment by rowbot-weisguy** [comment]
I just tried this with MetaMask, Rainbow and Trust. (all at latest versions from play store)

MetaMask: can connect to wallet consistently, but inconsistently offers the login signature request and fails to redirect when it is offered (token is retrieved)
Rainbow: can connect to wallet consistently, can log in consistently, fails to redirect on login (token is retrieved)
Trust: can connect to wallet consistently, can log in consistently, redirects work as expected

I don't have experience with Rainbow or Trust before this, but MetaMask feels like it degraded in experience overnight - it used to do connect + login with redirects at both steps just fine. Does anyone know what might have happened?

**Comment by iketw** [comment]
@rowbot-weisguy , what happened was that since yesterday MM and all these wallets and all our Sdks are using WalletConmect V2 as the new protocol. They used to use WalletConnect V1 but it was shutdown: 

https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

This is the main reason why so many new issues are popping up with MM.

**Comment by T-Damer** [comment]
@rowbot-weisguy same to me, if you'll find any workaround, please share with us :)

**Comment by rowbot-weisguy** [comment]
@T-Damer No workaround yet, but I'm lucky that the project I'm working on is not yet launched publicly. I'd be very anxious if this was happening and it was in production making it hard (sometimes requiring dozens of attempts) for users to log into our dapp.

**Comment by rowbot-weisguy** [comment]
Just wanted to report that this is still occurring. We have had to remove our `disabled` state on the login button so that our MetaMask users can attempt logging in as many times as required while the previous login requests variably hang.

**Comment by iketw** [comment]
> Just wanted to report that this is still occurring. We have had to remove our `disabled` state on the login button so that our MetaMask users can attempt logging in as many times as required while the previous login requests variably hang.

@rowbot-weisguy what version of the RN SDK are you on?

**Comment by rowbot-weisguy** [comment]
@iketw just reproduced this with `@thirdweb-dev/react-native@0.2.39`

**Comment by iketw** [comment]
@rowbot-weisguy, let's do two things:

1. We have released a new free API keys system that will make it faster to use thirdweb's services. You can create an API key here: https://thirdweb.com/dashboard/settings/api-keys and get a `clientId` from it to pass in the ThirdwebProvider (please, make sure to add your app's `bundleId` in the `Allowed Bundle IDs` when creating your api key):

```
<ThirdwebProvider clientId={'your-client-id'} ... />
```

Test with this clientId as it will use better RPCs to communicate with MM.

2. If you're still experiencing these issues, could you please maybe share a repo I can take a look at?

And just to confirm, Rainbow and Trust wallets are still working as expected correct? MM has a few issues opened in their repo related to the issue you're facing:

https://github.com/MetaMask/metamask-mobile/issues/6870

https://github.com/MetaMask/metamask-mobile/issues/6866

https://github.com/MetaMask/metamask-mobile/issues/6886

**Comment by T-Damer** [comment]
"@iketw I tried your approach, looks like MetaMask doesn't suggest to open connect at all with `ConnectButton`, but it suggest to connect and sign when using `useMetaMask` hook

**Comment by iketw** [comment]
@T-Damer I tested with our [react-native template project](https://github.com/thirdweb-example/react-native-typescript-starter) and I get redirected back to the app with all wallets (I have a video but just noticed I can't attach here :( )

I believe after connecting/disconnecting a few times the session fields WC stores in the device's AsyncStorage get messed up for some reason. I have added an update in version `2.5.1` where I'm clearing the wc fields stored in storage after disconnect is called. Hopefully this will do a clean connection every time you call connect.

Could you please try uninstalling/reinstalling the app and check if this fixes your issue?
