### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by paulrostorp** [thirdweb-dev/js#1393]
Getting the following error on the client on react:

```js
ReferenceError: process is not defined
    at getMultichainRegistryAddress (http://127.0.0.1:8788/build/_shared/chunk-A2AGZSEI.js:32062:3)
    at new MultichainRegistry (http://127.0.0.1:8788/build/_shared/chunk-BVOLDO2O.js:2613:55)
    at new ThirdwebSDK (http://127.0.0.1:8788/build/_shared/chunk-BVOLDO2O.js:3139:31)
    at http://127.0.0.1:8788/build/_shared/chunk-4CMVNCWC.js:3488:14
    at mountMemo (http://127.0.0.1:8788/build/_shared/chunk-R56VZJF5.js:12817:27)
    at Object.useMemo (http://127.0.0.1:8788/build/_shared/chunk-R56VZJF5.js:13141:24)
    at useMemo (http://127.0.0.1:8788/build/_shared/chunk-IRKISTRB.js:1094:29)
    at WrappedThirdwebSDKProvider (http://127.0.0.1:8788/build/_shared/chunk-4CMVNCWC.js:3463:41)
    at renderWithHooks (http://127.0.0.1:8788/build/_shared/chunk-R56VZJF5.js:12171:26)
    at mountIndeterminateComponent (http://127.0.0.1:8788/build/_shared/chunk-R56VZJF5.js:14921:21)
```

The error is coming from here: https://github.com/thirdweb-dev/js/blob/aa6bdd0809d1d5536c837c59b2d407ee974c1f9c/packages/sdk/src/evm/constants/addresses/getMultichainRegistryAddress.ts#L8

All I am doing is invoking the `ThirdwebSDKProvider` using esbuild with remix, the file is only executed in the browser.

**Comment by paulrostorp** [comment]
@MrSucik I'm on the latest version of all those packages

**Comment by iketw** [comment]
@paulrostorp thanks for reporting. We'll take a look into this and report back

**Comment by iketw** [comment]
@paulrostorp, we have merged a PR (https://github.com/thirdweb-dev/js/pull/1398#event-9927880140) where we check if process exist before using it. Feel free to try the sdk with version `@thirdweb-dev/react@nightly` and let me know if that fixes your issue, the final version will be released this week.

**Comment by paulrostorp** [comment]
@iketw That fixed it :)
