### ISSUE TITLE
getting 'require is not defined' with Vite/Nuxt

### ISSUE THREAD

**Issue by backface** [thirdweb-dev/js#1535]
Unfortunately, Updating to the latest SDK versions and new API Keys breaks my code and existing workaround (see: https://github.com/thirdweb-dev/js/issues/1168) for Nuxt3 with Vite.

I've updated the same sample project, see:
https://github.com/backface/thirdweb-nuxt-test

Trying to set up and run the project with ppm results in a "require is not defined" error when running ThirdwebSDK.fromPrivateKey with SecretKey on the backend.

```
ReferenceError: require is not defined                                                                                                                                                   13:27:23
    at file:///data/projects/dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:1057:24
    at Array.map (<anonymous>)
    at prepareGatewayUrls (file:///data/projects//dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:1050:52)                                                           13:26:44
    at new ThirdwebStorage (file:///data/projects/dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:1837:24)
    at createStorage (file:///data/projects/dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:38695:12)
    at new ThirdwebSDK (file:///data/projects/dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:39209:31)
    at ThirdwebSDK.fromPrivateKey (file:///data/projects/dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:39154:12)
    at file:///data/projects/dev/thirdweb-nuxt-test/.nuxt/dev/index.mjs:42205:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (file:///data/projects/dev/thirdweb-nuxt-test/node_modules/.pnpm/h3@1.6.6/node_modules/h3/dist/index.mjs:1255:19)

```

Using yarn already fails on startup with:

```
[worker reload] [worker init] Named export 'EventEmitter' not found. The requested module 'file:///data/projects/dev/thirdweb-nuxt-test/node_modules/eventemitter3/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:                                                                                                       13:19:59

import pkg from 'file:///data/projects/dev/thirdweb-nuxt-test/node_modules/eventemitter3/index.js';
const { EventEmitter: EventEmitter$1 } = pkg;


  import EventEmitter, { EventEmitter as EventEmitter$1 } from 'node_modules/eventemitter3/index.js';
  ^^^^^^^^^^^^
  SyntaxError: Named export 'EventEmitter' not found. The requested module 'node_modules/eventemitter3/index.js' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from 'node_modules/eventemitter3/index.js';
  const { EventEmitter: EventEmitter$1 } = pkg;
  
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

it seems there are some code wrongly imported from commonJS down the dependency chain?

**Comment by joaquim-verges** [comment]
thanks for the report @backface we're looking into this

**Comment by MananTank** [comment]
@backface We have released a fix the the Nuxt+Yarn issue (Named export 'EventEmitter' not found) in the latest nightly version 

Please install the latest nightly version of thirdweb packages ( `@thirdweb-dev/sdk@nightly`, `@thirdweb-dev/wallets@nightly` in your example )

Note that we have only fixed the issue Yarn issue, pnpm issue is not yet fixed so please use yarn for now

**Comment by backface** [comment]
> Note that we have only fixed the yarn issue, pnpm issue is not yet fixed so please use yarn for now

I'd have to change my development and deployment chain, therefore. any ideas on how long it takes to work with pnpm also?
