### ISSUE TITLE
Error Encountered When Running Code with `vite-node`

### ISSUE THREAD

**Issue by RSamaium** [thirdweb-dev/js#2002]
Hello,

I'm reaching out to report an issue I've encountered while using `vite-node`. When I try to execute my code using `vite-node`, I'm facing an error that prevents the code from running correctly. This issue does not occur when I run the same code with standard Node.js.

### Environment
- Node.js version: 18+
- Vite-node version: Latest
- Operating system: Linux
- ThirdWeb SDK: Latest

### Steps to Reproduce

https://stackblitz.com/edit/stackblitz-starters-b7pyzu?file=index.js

To test:
- `node index.js` : works
- `npm start` or `npx vite-node index.js`: not works

### Actual Behavior

```
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xfc575B22033dA2d86a52d8167B4fEd375c79f0Ab","data":"0x3b1475a7","accessList":null}, error={"reason":"missing response","code":"SERVER_ERROR","requestBody":"[{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xfc575b22033da2d86a52d8167b4fed375c79f0ab\",\"data\":\"0x3b1475a7\"},\"latest\"],\"id\":43,\"jsonrpc\":\"2.0\"}]","requestMethod":"POST","serverError":{},"url":"https://mumbai.rpc.thirdweb.com/"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at checkError (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:66:16)
    at StaticJsonRpcBatchProvider.eval (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
    at Generator.throw (<anonymous>)
    at rejected (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/providers/lib.esm/json-rpc-provider.js:17:65) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    to: '0xfc575B22033dA2d86a52d8167B4fEd375c79f0Ab',
    data: '0x3b1475a7',
    accessList: null
  },
  error: Error: missing response (requestBody="[{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xfc575b22033da2d86a52d8167b4fed375c79f0ab\",\"data\":\"0x3b1475a7\"},\"latest\"],\"id\":43,\"jsonrpc\":\"2.0\"}]", requestMethod="POST", serverError={}, url="https://mumbai.rpc.thirdweb.com/", code=SERVER_ERROR, version=web/5.7.1)
      at Logger.makeError (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at eval (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/web/src.ts/index.ts:292:28)
      at Generator.throw (<anonymous>)
      at rejected (/home/projects/stackblitz-starters-b7pyzu/node_modules/@ethersproject/web/lib.esm/index.js:13:65) {
    reason: 'missing response',
    code: 'SERVER_ERROR',
    requestBody: '[{"method":"eth_call","params":[{"to":"0xfc575b22033da2d86a52d8167b4fed375c79f0ab","data":"0x3b1475a7"},"latest"],"id":43,"jsonrpc":"2.0"}]',
    requestMethod: 'POST',
    serverError: TypeError: Referrer "client" is not a valid URL.
        at _0x40436c (https://stackblitzstartersb7pyzu-okmy.w-credentialless.staticblitz.com/blitz.95086023.js:352:593143)
        at _0x46d452._0x2ea0fe (https://stackblitzstartersb7pyzu-okmy.w-credentialless.staticblitz.com/blitz.95086023.js:352:603878)
        at Object.t.exports.fetch (node:internal/deps/undici/undici:194:308109) {
      [cause]: [TypeError]
    },
    url: 'https://mumbai.rpc.thirdweb.com/'
  }
}
```

Best regards,

**Comment by hsynlms** [comment]
I think this is related to https://github.com/ethers-io/ethers.js/issues/3536

It seems that the `skipFetchSetup` option has been removed in ethers.js v6 but Thirdweb SDK still requires v5.x. Unfortunately, there is no way to change the `skipFetchSetup` option value.

**Comment by hsynaldgrn** [comment]
@jnsdls we get same error in our Next.js v14 app too.

**Comment by MananTank** [comment]
@RSamaium - I can replicate the error with `vite-node`. Thanks @hsynaldgrn for the info on `skipFetchSetup`. We will look into

**Comment by hsynlms** [comment]
@MananTank I opened a PR for this https://github.com/thirdweb-dev/js/pull/2085
