### ISSUE TITLE
Unable to verify Thirdweb smart contract on Celo

### ISSUE THREAD

**Issue by kamikazechaser** [thirdweb-dev/js#2557]
According to the docs:

```js
import { ThirdwebSDK } from "@thirdweb-dev/sdk";

const sdk = new ThirdwebSDK("celo", {
    secretKey: "XXX",
})
const explorerAPIUrl = "https://api.celoscan.io/api"
const explorerAPIKey = "XXX"

await sdk.verifier.verifyThirdwebContract(
    "ManagedAccountFactory",
    explorerAPIUrl,
    explorerAPIKey,
);
```

Output:

```bash
/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/index-1e72d576.cjs.dev.js:5109
      throw new Error("Can't resolve constructor arguments");
            ^

Error: Can't resolve constructor arguments
    at /tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/index-1e72d576.cjs.dev.js:5109:13
    at Array.map (<anonymous>)
    at encodeConstructorParamsForImplementation (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/index-1e72d576.cjs.dev.js:5075:70)
    at Object.computeDeploymentInfo (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/index-1e72d576.cjs.dev.js:5041:29)
    at Object.getDeploymentInfo (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/deployContractDeterministic-31e620a3.cjs.dev.js:140:76)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async predictThirdwebContractAddress (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/sdk-3a69b331.cjs.dev.js:120:28)
    at async getThirdwebContractAddress (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/sdk-3a69b331.cjs.dev.js:147:27)
    at async verifyThirdwebPrebuiltImplementation (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/sdk-3a69b331.cjs.dev.js:203:27)
    at async ContractVerifier.verifyThirdwebContract (/tmp/thirdweb/node_modules/.pnpm/@thirdweb-dev+sdk@4.0.50_ethers@5.7.2_typescript@5.4.3/node_modules/@thirdweb-dev/sdk/dist/sdk-3a69b331.cjs.dev.js:525:18)

Node.js v21.7.1 with sdk version ^4.0.50
```

Edit:

I tried to verify on the Dashboard. It reports the verification as successful but on Celoscan it isn't verfied. That is a separate bug related to the Thirdweb SaaS.

**Comment by kumaryash90** [comment]
Hey @kamikazechaser we're having some trouble currently with contract verification on Celo. 
We're looking into it. Will let you know once this is resolved.
