### ISSUE TITLE
editionDrop.history.getAllClaimerAddresses(0) error

### ISSUE THREAD

**Issue by changjiashuai** [thirdweb-dev/js#275]
const walletAddresses = (await editionDrop).history.getAllClaimerAddresses(0);  

reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 413,
  headers: {
    'access-control-allow-credentials': 'true',
    'access-control-allow-headers': 'Content-Type,Authorization,User-Agent',
    'access-control-allow-methods': 'GET, POST, OPTIONS',
    'access-control-allow-origin': '',
    'content-type': 'application/json',
    vary: 'Accept-Encoding',
    'x-host-id': '',
    'x-node-id': '08777362-575c-4584-aa42-4f09eb19af92',
    'x-ratelimit-limit': '1000000',
    'x-ratelimit-remaining': '999814',
    'x-ratelimit-reset': '1665137764',
    'x-request-id': 'e0da4b42-61d3-4133-9d57-dc40d2852d36',
    date: 'Fri, 07 Oct 2022 05:18:57 GMT',
    'content-length': '142',
    connection: 'close'
  },
  body: '{"jsonrpc":"2.0","id":44,"result":null,"error":{"code":-32602,"message":"eth_getLogs and eth_newFilter are limited to a 10,000 blocks range"}}',
  requestBody: '{"method":"eth_getLogs","params":[{"fromBlock":"0x0","toBlock":"latest","address":"0x1d6288e8c07ceb1caa82c1ba4fcc856e7536b2d8","topics":["0x4f72e6585331094d368e469f11198272039d08cbddfcda1577e192687a83afb6"]}],"id":44,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://aged-dimensional-mansion.ethereum-goerli.discover.quiknode.pro/xxxx'
}

**Comment by legiarung** [comment]
I also get the same error, for polygon network and mumbai testnet it is.
```
Error: eth_getLogs and eth_newFilter are limited to a 10,000 blocks range
    at json-rpc-batch-provider.ts:70:1
    at Array.forEach (<anonymous>)
    at json-rpc-batch-provider.ts:67:1
```

**Comment by joaquim-verges** [comment]
this generally is a limitation of the RPC provider you're using - can you try with Alchemy? they're pretty good with their limits
