### ISSUE TITLE
Error with SvelteKit

### ISSUE THREAD

**Issue by NoelJacob** [thirdweb-dev/js#484]
```
/usr/bin/npm run dev

> xdc@0.0.1 dev
> vite dev



  VITE v4.0.4  ready in 1662 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
10:32:13 pm [vite-plugin-svelte] ssr compile in progress ...
/home/john/Desktop/xdc/node_modules/.pnpm/@thirdweb-dev+sdk@3.6.9_ethers@5.7.2/node_modules/@thirdweb-dev/sdk/dist/thirdweb-checkout-058de62a.cjs.dev.js:1116
  return CONTRACT_ADDRESSES[chainId][contractName];
                                    ^

TypeError: Cannot read properties of undefined (reading 'twFactory')
    at getContractAddressByChainId (/home/john/Desktop/xdc/node_modules/.pnpm/@thirdweb-dev+sdk@3.6.9_ethers@5.7.2/node_modules/@thirdweb-dev/sdk/dist/thirdweb-checkout-058de62a.cjs.dev.js:1116:37)
    at /home/john/Desktop/xdc/node_modules/.pnpm/@thirdweb-dev+sdk@3.6.9_ethers@5.7.2/node_modules/@thirdweb-dev/sdk/dist/thirdweb-checkout-058de62a.cjs.dev.js:17116:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.3.0

Process finished with exit code 1


```

**Comment by joaquim-verges** [comment]
How are you initializing the thirdweb SDK here? we're also about to merge a change that touches this code and should help
