### ISSUE TITLE
Error when try sign in next.js/account abstraction

### ISSUE THREAD

**Issue by zpoken** [thirdweb-dev/js#5087]
```
Failed to log in Error: Module [project]/node_modules/.pnpm/thirdweb@5.63.1_@types+react@18.3.11_bufferutil@4.0.8_react-dom@18.3.1_react@18.3.1__react@18_czng5dldzohr4em4k4qr4pvkcq/node_modules/thirdweb/dist/esm/utils/bytecode/is-contract-deployed.js [app-client] (ecmascript, async loader) was instantiated because it was required from module [project]/node_modules/.pnpm/thirdweb@5.63.1_@types+react@18.3.11_bufferutil@4.0.8_react-dom@18.3.1_react@18.3.1__react@18_czng5dldzohr4em4k4qr4pvkcq/node_modules/thirdweb/dist/esm/wallets/smart/index.js [app-client] (ecmascript), but the module factory is not available. It might have been deleted in an HMR update.
    at instantiateModule (d9c5a_next_dist_esm_build_templates_app-page_f5835b.js:494:15)
    at getOrInstantiateModuleFromParent (d9c5a_next_dist_esm_build_templates_app-page_f5835b.js:609:12)
    at commonJsRequire (d9c5a_next_dist_esm_build_templates_app-page_f5835b.js:146:20)
    at Object.signMessage (node_modules__pnpm_5a72c2._.js:8550:17)
    at signLoginPayload (b987e_thirdweb_dist_esm_c62d45._.js:368:37)
    at Object.mutationFn (b987e_thirdweb_dist_esm_react_core_b0d0dc._.js:230:41)

```
I use this example - https://github.com/thirdweb-example/thirdweb-auth-next

**Comment by zpoken** [comment]
```
'use client'
import type { NextPage } from 'next'
import { ConnectButton } from 'thirdweb/react'
import { sepolia } from 'thirdweb/chains'
import { client } from '../../lib/client'
import { generatePayload, isLoggedIn, login, logout } from './actions/auth'

const ConnectButtonPage: NextPage = () => {
	return (
		<ConnectButton
			client={client}
			accountAbstraction={{
				chain: sepolia,
				factoryAddress: '0x1b8e4A65aA0A40dC76772A82047C6F40258632D7',
				sponsorGas: true,
			}}
			auth={{
				isLoggedIn: async address => {
					console.log('checking if logged in!', { address })
					return await isLoggedIn()
				},
				doLogin: async params => {
					console.log('logging in!')
					await login(params)
				},
				getLoginPayload: async ({ address }) =>
					generatePayload({ address, chainId: sepolia.id }),
				doLogout: async () => {
					console.log('logging out!')
					await logout()
				},
			}}
		/>
	)
}
```

**Comment by joaquim-verges** [comment]
Thanks for the report @zpoken . I think this has to do with next's turbo feature.

Can you remove `--turbo` from the `dev` script in your `package.json` ? That should fix it for now.

We're currently looking into supporting next turbo feature so that you can keep using it. Cc @MananTank

**Comment by gregfromstl** [comment]
Looks like this has been resolved, feel free to reopen the issue if you're still having trouble
