### ISSUE TITLE
SyntaxError: Unexpected token '&&='

### ISSUE THREAD

**Issue by amunrarara** [thirdweb-dev/js#999]
First time I've seen an &&= in JS. In my NextJS project, this line is throwing an error during compilation. Any ideas?

Stack trace (ws-web-client:dev spam from Turborepo):

```
ws-web-client:dev: error - /Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/sdk/dist/watchTransactions-e5d8e227.cjs.dev.js:6547
ws-web-client:dev:       foundError &&= error.includes(substring);
ws-web-client:dev:                  ^^^
ws-web-client:dev: 
ws-web-client:dev: SyntaxError: Unexpected token '&&='
ws-web-client:dev:     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1049:27)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/sdk/dist/thirdweb-dev-sdk.cjs.dev.js:6:25)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/sdk/dist/thirdweb-dev-sdk.cjs.js:6:20)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/wallets/evm/wallets/smart-wallet/dist/thirdweb-dev-wallets-evm-wallets-smart-wallet.cjs.dev.js:8:11)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/wallets/dist/thirdweb-dev-wallets.cjs.dev.js:23:76)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/wallets/dist/thirdweb-dev-wallets.cjs.js:6:20)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.cjs.dev.js:5:15)
ws-web-client:dev:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ws-web-client:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ws-web-client:dev:     at Module.load (internal/modules/cjs/loader.js:950:32)
ws-web-client:dev:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ws-web-client:dev:     at Module.require (internal/modules/cjs/loader.js:974:19)
ws-web-client:dev:     at require (internal/modules/cjs/helpers.js:101:18)
ws-web-client:dev:     at Object.<anonymous> (/Volumes/T7Touch/Projects/WorldSpark/Repos/marketplace/node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.cjs.js:6:20) {
ws-web-client:dev:   digest: undefined
ws-web-client:dev: }
```

**Comment by amunrarara** [comment]
This issue is also preventing my Vercel build. I'll have to roll back the version
<img width="1440" alt="Screen Shot 2023-05-11 at 1 34 15 PM" src="https://github.com/thirdweb-dev/js/assets/21048358/330da718-fb17-45e3-bf08-649d602d8117">
